Cleaned up gas limit display to remain consistent when loading page & no limit set
flexpool/frontend pull request #122
Opened 2021-04-19 12:52 UTC by HippityHoppityXD

Added Skeleton to Gas Limit when loading
Gas limit now also displays as "None Set" when no limit is set rather than not showing in heading.

2021-04-19 17:27 UTC, AlexSSD7 requested changes
Thank you for the contribution! I've requested some changes.

2021-04-19 17:27 UTC, AlexSSD7 commented on src/pages/MinerDashboard/Header/MinerDetails.tsx
> +            </Tooltip>*/}
Remove this commented block, please.

2021-04-19 17:27 UTC, AlexSSD7 commented on src/pages/MinerDashboard/Header/MinerDetails.tsx
> +          <div>None Set&nbsp;&nbsp;
This should be just gray `None`.

2021-04-19 17:27 UTC, AlexSSD7 commented on src/pages/MinerDashboard/Header/MinerDetails.tsx
> +          <div>Gas Limit:&nbsp;</div>
First, this should be "Gas Price Limit". Gas Limit is a completely different thing.

Also, this value name should change depending on the coin selected. With Ethereum it is Gas Price, with Bitcoin it is sat/b, etc. This is why the generic `maxFeePrice` name was chosen in the API. cc @march08

2021-04-20 11:53 UTC, AlexSSD7 approved these changes
Looks ok to me. @march08 please review this one as well.

2021-04-20 12:11 UTC, march08 approved these changes
Good to go, thanks for PR!

2021-04-20 12:11 UTC, merged