Refactor SearchAddressBar
flexpool/frontend pull request #123
Opened 2021-04-19 13:17 UTC by evangunawan

- Open latest history address on search button click.
- Update storage on Address Cahce Result item click.

2021-04-19 17:36 UTC, AlexSSD7 approved these changes
LGTM. @march08 review this one too, please.

2021-04-20 09:24 UTC, march08 requested changes

2021-04-20 10:55 UTC, evangunawan commented on src/components/SearchAddressBar/SearchAddressBar.tsx
> +      let searchAddress: string = address || searchData[0]?.address;
fixed on latest commit. Thank you for reviewing, hope it helps!

2021-04-20 12:06 UTC, march08 commented
great, looks good, thanks for contrib!

2021-04-20 12:07 UTC, march08 approved these changes

2021-04-20 12:07 UTC, merged