Add flexfarmer annotation
flexpool/frontend pull request #418
Opened 2021-08-31 15:45 UTC by aminick

Ref #408 

![image](https://user-images.githubusercontent.com/5182324/131534141-226e485f-6436-410c-b30a-13a1cc624213.png)

2021-08-31 15:46 UTC, aminick commented
Need style review @AlexSSD7

2021-09-03 08:30 UTC, AlexSSD7 requested changes
![image](https://user-images.githubusercontent.com/43043344/131975300-3be43137-3438-4ecd-bb6a-eede7c7d9589.png)

No loading animation for reported hashrate.

2021-09-03 11:45 UTC, aminick commented
Fixed: 
![image](https://user-images.githubusercontent.com/5182324/132000179-9a976a71-15d7-42eb-aa07-e312d3ab0070.png)

2021-09-03 14:31 UTC, AlexSSD7 approved these changes
LGTM

2021-09-03 14:32 UTC, merged