Improve new user dashboard experience
flexpool/frontend pull request #451
Opened 2021-09-25 10:47 UTC by aminick

2021-09-25 12:31 UTC, AlexSSD7 requested changes
https://frontend-git-404-improve-miner-404-flexpool.vercel.app/miner/eth/0x90935d9456BBE0C0Ba7D2C54D6916A92aE53e091invalidaddress

I guess it should get back to 404 if the entered address is invalid (doesn't match the regexes provided somewhere in the codebase, don't recall).

2021-09-26 13:55 UTC, aminick commented
@AlexSSD7 Updated validation logic and did some minor UI tweaks as well.

<img width="1237" alt="Screen Shot 2021-09-26 at 21 53 17" src="https://user-images.githubusercontent.com/5182324/134810910-91c59897-c1fa-4df6-8a75-157021880671.png">

2021-09-26 16:57 UTC, AlexSSD7 approved these changes

2021-09-26 16:58 UTC, merged

2021-09-27 12:11 UTC, aminick commented
Fix #444